modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="https://github.com/Patbox/TextPlaceholderAPI/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="https://github.com/Patbox/TextPlaceholderAPI"
logoFile="assets/placeholderapi/icon.png"
authors="${authors}"
description='''${description}'''

[[dependencies.${id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${id}]]
    modId="minecraft"
    type="required"
    versionRange="${mc}"
    ordering="NONE"
    side="BOTH"
