modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
    modId="${modId}"
    version="${version}"
    displayName="${modName}"
    displayURL="${homepage}"
    logoFile="assets/icon.png"
    authors="${authors}"
    description='''${modDescription}'''

[[dependencies.${modId}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modId}]]
    modId="minecraft"
    type="required"
    versionRange="[${mc},)"
    ordering="NONE"
    side="BOTH"
