modLoader="javafml"
loaderVersion="[4,)"
license="LGPLv3"
issueTrackerURL="https://pb4.eu"

[[mods]]
modId="testmod"
version="1.0.0"
displayName="Test Mod"
displayURL="https://pb4.eu"
authors="Patbox"
description=''''''

[[dependencies.testmod]]
    modId="neoforge"
    type="required"
    versionRange="[${neo},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.testmod]]
    modId="minecraft"
    type="required"
    versionRange="${mc}"
    ordering="NONE"
    side="BOTH"
