modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="testmod"
version="1.0.0"
displayName="Test Mod"
displayURL="${homepage}"
authors="${authors}"
description=''''''

[[dependencies.testmod]]
    modId="neoforge"
    type="required"
    versionRange="[${neo},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.testmod]]
    modId="minecraft"
    type="required"
    versionRange="[${mc},)"
    ordering="NONE"
    side="BOTH"
